version: "3.8"
services:
  mongodb:
    image: mongo:7.0
    container_name: smart-farm-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: farmpass123
      MONGO_INITDB_DATABASE: smart_farm_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
